use_frameworks!

platform :ios, '8.0'

target 'MCTestModule_Example' do
  pod 'MCTestModule', :path => '../'

  target 'MCTestModule_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
